/**
 * The logo, as vector geometry.
 *
 * GENERATED by scripts/generate-icons.mjs -- do not edit by hand. The same
 * numbers produce the launcher icon, the adaptive and monochrome layers, the
 * splash mark and the in-app <Logo />, so none of them can drift apart.
 */

export const LOGO_VIEW_BOX = '0 0 500 500';
export const LOGO_STROKE_WIDTH = 50;

/** Two arcs: the left ring, then the right, each broken at one crossing. */
export const LOGO_PATHS = [
  'M 279.28 196.59 A 118.5 118.5 0 1 1 208.56 136.80',
  'M 220.72 303.41 A 118.5 118.5 0 1 1 291.44 363.20',
] as const;
