const { withEntitlementsPlist, withAndroidManifest } = require('expo/config-plugins');

/**
 * Config plugin for Unbreakable Lock.
 *
 * Everything here is regenerated by `npx expo prebuild`, so the ios/ and
 * android/ folders stay disposable.
 *
 * iOS: adds the Family Controls entitlement and the App Group that the app and
 *      its DeviceActivityMonitor extension use to share state.
 *      Note: `com.apple.developer.family-controls` must ALSO be enabled for
 *      your App ID in the Apple Developer portal, which requires Apple to
 *      approve a Family Controls (distribution) request. Without that approval
 *      the entitlement is present but authorization fails at runtime, and the
 *      app reports ENTITLEMENT_UNAVAILABLE rather than faking a lock.
 *
 * Android: the enforcement permissions live in the native module's own
 *      AndroidManifest.xml and are merged automatically. This plugin only marks
 *      the app as needing legacy external-storage-free, cleartext-free defaults
 *      untouched -- it deliberately does nothing extra so nothing surprising is
 *      injected into the manifest.
 */

const DEFAULT_APP_GROUP = 'group.com.unbreakablelock.app';

const withFamilyControls = (config, { appGroup }) =>
  withEntitlementsPlist(config, (mod) => {
    mod.modResults['com.apple.developer.family-controls'] = true;

    const groups = new Set(mod.modResults['com.apple.security.application-groups'] || []);
    groups.add(appGroup);
    mod.modResults['com.apple.security.application-groups'] = Array.from(groups);

    return mod;
  });

/**
 * The module manifest already declares what enforcement needs. We assert the
 * merge actually happened so a silent manifest-merger change surfaces at build
 * time instead of at runtime on a user's phone.
 */
const withManifestAssertion = (config) =>
  withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;
    manifest['uses-permission'] = manifest['uses-permission'] || [];

    const required = [
      'android.permission.FOREGROUND_SERVICE',
      'android.permission.RECEIVE_BOOT_COMPLETED',
    ];

    for (const name of required) {
      const present = manifest['uses-permission'].some(
        (entry) => entry.$?.['android:name'] === name
      );
      if (!present) {
        manifest['uses-permission'].push({ $: { 'android:name': name } });
      }
    }

    return mod;
  });

module.exports = function withUnbreakableLock(config, props = {}) {
  const appGroup = props.appGroup || DEFAULT_APP_GROUP;
  let next = withFamilyControls(config, { appGroup });
  next = withManifestAssertion(next);
  return next;
};
